### ISSUE TITLE
emscripten tot regression "unexpected runtime library name: roundevenf"

### ISSUE THREAD

**Issue by mr-c** [simd-everywhere/simde#1001]
https://github.com/simd-everywhere/simde/actions/runs/4553452414/jobs/8030030651#step:8:463

@tlively Could you dig into this? Many thanks!

```
FAILED: test/x86/sse2-emul-c.js.p/sse2.c.o 
/opt/emsdk/upstream/emscripten/emcc -Itest/x86/sse2-emul-c.js.p -Itest/x86 -I../test/x86 -I. -I.. -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -O2 -g -Weverything -fno-lax-vector-conversions -Werror -O2 -msimd128 -Wno-unsafe-buffer-usage -fopenmp-simd -DSIMDE_CONSTRAINED_COMPILATION -DSIMDE_ENABLE_OPENMP -Wno-psabi -DSIMDE_TEST_BARE -DSIMDE_NO_NATIVE -MD -MQ test/x86/sse2-emul-c.js.p/sse2.c.o -MF test/x86/sse2-emul-c.js.p/sse2.c.o.d -o test/x86/sse2-emul-c.js.p/sse2.c.o -c ../test/x86/sse2.c
unexpected runtime library name: roundevenf
UNREACHABLE executed at /b/s/w/ir/cache/builder/emscripten-releases/llvm-project/llvm/lib/Target/WebAssembly/WebAssemblyRuntimeLibcallSignatures.cpp:891!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -DEMSCRIPTEN -Werror=implicit-function-declaration --sysroot=/opt/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -Itest/x86/sse2-emul-c.js.p -Itest/x86 -I../test/x86 -I. -I.. -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -O2 -g3 -Weverything -fno-lax-vector-conversions -Werror -O2 -msimd128 -Wno-unsafe-buffer-usage -fopenmp-simd -DSIMDE_CONSTRAINED_COMPILATION -DSIMDE_ENABLE_OPENMP -Wno-psabi -DSIMDE_TEST_BARE -DSIMDE_NO_NATIVE -MD -MQ test/x86/sse2-emul-c.js.p/sse2.c.o -MF test/x86/sse2-emul-c.js.p/sse2.c.o.d -c ../test/x86/sse2.c -o test/x86/sse2-emul-c.js.p/sse2.c.o
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '../test/x86/sse2.c'.
4.	Running pass 'WebAssembly Assembly Printer' on function '@__original_main'
 #0 0x00007f3302c019e8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/emsdk/upstream/bin/../lib/libLLVM-17git.so+0x1bbc9e8)
 #1 0x00007f3302bff6be llvm::sys::RunSignalHandlers() (/opt/emsdk/upstream/bin/../lib/libLLVM-17git.so+0x1bba6be)
 #2 0x00007f3302c00d51 llvm::sys::CleanupOnSignal(unsigned long) (/opt/emsdk/upstream/bin/../lib/libLLVM-17git.so+0x1bbbd51)
 #3 0x00007f3302b47a56 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #4 0x00007f3300c1f520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #5 0x00007f3300c73a7c pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x96a7c)
 #6 0x00007f3300c1f476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #7 0x00007f3300c057f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #8 0x00007f3302b590c0 llvm::install_out_of_memory_new_handler() (/opt/emsdk/upstream/bin/../lib/libLLVM-17git.so+0x1b140c0)
 #9 0x00007f3304f54dfd (/opt/emsdk/upstream/bin/../lib/libLLVM-17git.so+0x3f0fdfd)
#10 0x00007f3304eeaee7 llvm::WebAssemblyAsmPrinter::getOrCreateWasmSymbol(llvm::StringRef) WebAssemblyAsmPrinter.cpp:0:0
#11 0x00007f3304eeb2df llvm::WebAssemblyAsmPrinter::emitDecls(llvm::Module const&) WebAssemblyAsmPrinter.cpp:0:0
#12 0x00007f3304eedee7 llvm::WebAssemblyAsmPrinter::emitConstantPool() WebAssemblyAsmPrinter.cpp:0:0
#13 0x00007f330370f5bc llvm::AsmPrinter::emitFunctionHeader() (/opt/emsdk/upstream/bin/../lib/libLLVM-17git.so+0x26ca5bc)
#14 0x00007f33037123cd llvm::AsmPrinter::emitFunctionBody() (/opt/emsdk/upstream/bin/../lib/libLLVM-17git.so+0x26cd3cd)
#15 0x00007f3304eee8ab llvm::WebAssemblyAsmPrinter::runOnMachineFunction(llvm::MachineFunction&) WebAssemblyAsmPrinter.cpp:0:0
#16 0x00007f33030c95b9 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/opt/emsdk/upstream/bin/../lib/libLLVM-17git.so+0x20845b9)
#17 0x00007f3302d93aa7 llvm::FPPassManager::runOnFunction(llvm::Function&) (/opt/emsdk/upstream/bin/../lib/libLLVM-17git.so+0x1d4eaa7)
#18 0x00007f3302d9bfc2 llvm::FPPassManager::runOnModule(llvm::Module&) (/opt/emsdk/upstream/bin/../lib/libLLVM-17git.so+0x1d56fc2)
#19 0x00007f3302d945cb llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/emsdk/upstream/bin/../lib/libLLVM-17git.so+0x1d4f5cb)
#20 0x00007f330829015e clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::__2::unique_ptr<llvm::raw_pwrite_stream, std::__2::default_delete<llvm::raw_pwrite_stream>>) (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.17git+0x2bd315e)
#21 0x00007f330867f290 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) CodeGenAction.cpp:0:0
#22 0x00007f3306fa20d6 clang::ParseAST(clang::Sema&, bool, bool) (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.17git+0x18e50d6)
#23 0x00007f3308db937f clang::FrontendAction::Execute() (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.17git+0x36fc37f)
#24 0x00007f3308d2aa5d clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.17git+0x366da5d)
#25 0x00007f3308e3e9cf clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.17git+0x37819cf)
#26 0x0000555d99a9401f cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/emsdk/upstream/bin/clang+0x1701f)
#27 0x0000555d99a8ff6b ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#28 0x00007f33089b8909 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::__2::optional<llvm::StringRef>>, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>*, bool*) const::$_0>(long) Job.cpp:0:0
#29 0x00007f3302b47796 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/emsdk/upstream/bin/../lib/libLLVM-17git.so+0x1b02796)
#30 0x00007f33089b80d2 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::__2::optional<llvm::StringRef>>, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>*, bool*) const (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.17git+0x32fb0d2)
#31 0x00007f330897742c clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.17git+0x32ba42c)
#32 0x00007f330897771e clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::__2::pair<int, clang::driver::Command const*>>&, bool) const (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.17git+0x32ba71e)
#33 0x00007f3308998aa0 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::__2::pair<int, clang::driver::Command const*>>&) (/opt/emsdk/upstream/bin/../lib/libclang-cpp.so.17git+0x32dbaa0)
#34 0x0000555d99a8efdc clang_main(int, char**, llvm::ToolContext const&) (/opt/emsdk/upstream/bin/clang+0x11fdc)
#35 0x0000555d99a9f9c1 main (/opt/emsdk/upstream/bin/clang+0x229c1)
#36 0x00007f3300c06d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#37 0x00007f3300c06e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#38 0x0000555d99a8bfaa _start (/opt/emsdk/upstream/bin/clang+0xefaa)
clang: error: clang frontend command failed with exit code 134 (use -v to see invocation)
clang version 17.0.0 (https://github.com/llvm/llvm-project 1bb8d5d8fb73f304ca84dddacb8c162418490644)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /opt/emsdk/upstream/bin
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/sse2-7bec74.c
clang: note: diagnostic msg: /tmp/sse2-7bec74.sh
clang: note: diagnostic msg: 

********************
emcc: error: '/opt/emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -DEMSCRIPTEN -Werror=implicit-function-declaration --sysroot=/opt/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -Itest/x86/sse2-emul-c.js.p -Itest/x86 -I../test/x86 -I. -I.. -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -O2 -g3 -Weverything -fno-lax-vector-conversions -Werror -O2 -msimd128 -Wno-unsafe-buffer-usage -fopenmp-simd -DSIMDE_CONSTRAINED_COMPILATION -DSIMDE_ENABLE_OPENMP -Wno-psabi -DSIMDE_TEST_BARE -DSIMDE_NO_NATIVE -MD -MQ test/x86/sse2-emul-c.js.p/sse2.c.o -MF test/x86/sse2-emul-c.js.p/sse2.c.o.d -c ../test/x86/sse2.c -o test/x86/sse2-emul-c.js.p/sse2.c.o' failed (returned 1)
```

**Comment by tlively** [comment]
Bisecting LLVM to find the culprit now.

**Comment by tlively** [comment]
The bad commit is https://github.com/llvm/llvm-project/commit/a7d6593a0a17a1e7f46a3c9cd5c4aeeb7dfc6e0a.

I assume the fix is to add support for these newly-generated builtin functions to the Wasm backend. I'll take a look at that now.

**Comment by tlively** [comment]
Fix is up for review: https://reviews.llvm.org/D147476

**Comment by tlively** [comment]
The fix is landed and should be rolled into the latest `tot` release.

**Comment by mr-c** [comment]
Thank you @tlively ! When is the next tot release expected?

**Comment by mr-c** [comment]
I'm still seeing the error at https://github.com/simd-everywhere/simde/actions/runs/4584536590/jobs/8162344254#step:8:609

**Comment by tlively** [comment]
Aha, it looks like the compiler error is fixed, but now we're getting a link error because `roundeven` and `roundevenf` aren't getting shipped as part of our system libraries. Will talk with the team about how to fix that.

**Comment by tlively** [comment]
So these functions are newly introduced in C23 and musl doesn't support them yet, so there's no good way for Emscripten to support them yet, either. Is there a way you can avoid emitting calls to them?

**Comment by mr-c** [comment]
Thanks for the troubleshooting @tlively ; SIMDe isn't using C23 `roundeven`/`roundevenf`, but it is using `__builtin_roundeven`/`__builtin_roundevenf` if the compiler defines it:

https://github.com/simd-everywhere/simde/blob/e861f2c87fcde95b632ec0941ec7f8509d7568ce/simde/simde-math.h#L1167-L1171

It is a bit funny from my perspective if a compiler defines a function that later won't work :-P 

Of course, one can add an opt-out for emscripten at the above location.

Though if you could contribute a WASM implementation instead of an opt-out, that'd be great :-)

**Comment by tlively** [comment]
I'm somewhat surprised that Wasm is the only platform with this problem, since even the LLVM libc doesn't supply `roundeven` yet and plenty of platforms also use musl. It definitely is surprising that Emscripten supports `__builtin_roundeven` in the frontend without actually supporting it in libraries, but that's an artifact of the separation between the clang frontend and backends and how all these code bases get pulled together.

For now I think the opt-out is the best solution until musl implements roundeven.

**Comment by mr-c** [comment]
@tlively Sure, I'll implement an opt-out. Can you open an emscripten bug for us to subscribe to, so we'll know when to remove it?

**Comment by tlively** [comment]
Sure, I've filed https://github.com/emscripten-core/emscripten/issues/19179.

**Comment by mr-c** [comment]
FYI, compiling SIMDe with `emcc -O3` no longer produces this error using the tot release
